### ISSUE TITLE
Le service cryptpad ne démarre pas sur Raspberry Pi 502 bad gateway

### ISSUE THREAD

**Issue by Rafi594** [YunoHost-Apps/cryptpad_ynh#10]
Bonjour

J'ai un problème avec cryptpad le service ne démarre pas sur un Raspberry Pi avec 1 GB de RAM et 400 Mo restants.

Quand il y avait le problème que la page de création d'un pad tournait sans s'arrêter j'avais quand même accès à la page d'accueil.

**Comment by JimboJoe** [comment]
Can you please try to install the latest version (directly from the repo, it's not in community.json yet), and report here the log in `/var/log/cryptpad/cryptpad.log`?

**Comment by Rafi594** [comment]
It work fine with the repo version
