### ISSUE TITLE
Upgrade failed

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/cryptpad_ynh#100]
### Describe the bug

An error occured during the execution of te upgrade script.

### Context

- Hardware: *desktop pc*
- YunoHost version: 4.2.6.1
- I have access to my server: ssh and webmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
  - If yes, please explain:
- Using, or trying to install package version/branch: master
- If upgrading, current package version: *4.7.0*

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    sudo yunohost app upgrade
    ```

### Expected behavior
Upgrade

### Logs

https://paste.yunohost.org/raw/doculuqoru

**Comment by Ddataa** [comment]
Hello @stemy2 

is this issue still valid ?
