### ISSUE TITLE
Include installMethod property in server telemetry

### ISSUE THREAD

**Issue by ansuz** [YunoHost-Apps/cryptpad_ynh#102]
### Describe the bug

I don't necessarily consider this a bug, but rather a way for you (the YunoHost-CryptPad package maintainers) to help us (the CryptPad core development team) to provide a safer platform.

#### The short version

Please set the `installMethod` property of the nodejs server's config file to a custom string indicating that the server was installed via YunoHost.

#### The detailed version

By default, the CryptPad server sends some telemetry to a server that our team administrates at launch time and every 24 hours thereafter. The complete details of the telemetry are logged by the server whenever they are sent. In case you were unaware or are curious about what is shared with our team you can search the node server's logs with `grep SERVER_TELEMETRY /path/to/your/logs/*`.

Most of the time we only pay attention to the number of unique IPs that send this telemetry. This counts in our favour when we write grant proposals that indicate how widely the software is used.

Recently we've been trying to engage administrators to encourage them to:

1. update to recent versions of the software so that we can be more proactive about disclosing security flaws and improvements
2. use the available self-diagnostic features to configure their instance securely (as referenced in #98)

During some periodic reviews of this telemetry data we noticed some patterns, like relatively large numbers of instances running particular (outdated) versions of the platform. We suspect this is a result of third-party packages or install scripts hardcoding those versions. Our [4.8.0 release](https://github.com/xwiki-labs/cryptpad/releases/tag/4.8.0) added an `installMethod` property to this server telemetry. By default this has a value of `unspecified`. [This PR to the community-maintained docker repo](https://github.com/xwiki-labs/cryptpad-docker/pull/26) set custom strings (`docker`, `docker-alpine`) for variants of the docker config files.

Including this value in telemetry would help us identify or rule out YunoHost as a source of commonly misconfigured instances and work with you to fix avoidable errors in the future, if necessary.

### Context

I am the project lead for the CryptPad platform and it would be helpful to be able to easily identify which third-party instances were installed via YunoHost.

### Steps to reproduce

1. Launch a CryptPad server running 4.8.0 or  later
2. scan its logs for a line including the string `SERVER_TELEMETRY`
3. determine whether the JSON included in this line contains the string `'unpecified'` or a custom _YunoHost-specific_ value.

### Expected behavior

* CryptPad instances installed using YunoHost provide a value in their telemetry data that allows the project's core developers to distinguish them from instances installed via alternative methods

### Logs

```json
["INFO","2021-08-17T05:48:06.706Z","SERVER_TELEMETRY",{"version":"4.10.0","installMethod":"this should say YunoHost","httpUnsafeOrigin":"http://localhost:3000","adminEmail":"some-guy@my.website","consentToContact":true,"instancePurpose":"experiment"}]
```

**Comment by Ddataa** [comment]
this has been added to latest version
