### ISSUE TITLE
Augmenter la taille de l'espace Cryptdrive

### ISSUE THREAD

**Issue by Rafi594** [YunoHost-Apps/cryptpad_ynh#11]
Bonjour

Est-il possible d'augmenter l'espace de stockage disponible dans le Cryptdrive ?

**Comment by JimboJoe** [comment]
I've just committed the new version update, and now we use the latest configuration file.
You can tune what you want by setting [this parameter](https://github.com/xwiki-labs/cryptpad/blob/master/config.example.js#L164) in `/var/www/cryptpad/config.js`.
