### ISSUE TITLE
Remove the sign up link

### ISSUE THREAD

**Issue by Rafi594** [YunoHost-Apps/cryptpad_ynh#13]
Hi 

It is possible to remove the sign up link in the main site ?

**Comment by frju365** [comment]
why ?

**Comment by frju365** [comment]
This is integrated in the application ... but ok... we can add the choice in the manifest.json (and disable it for private installation.)

**Comment by croulibri** [comment]
Is this possibility implemented yet ?
I would be interested to remove the sign up link in the main site in order to keek my install private.

**Comment by frju365** [comment]
In fact, so, choice will be added (quite 2years later) in registration, same for the email.

**Comment by ericgaspar** [comment]
Closing
