### ISSUE TITLE
4.11.0 to 5.2.1: fail to open services and previous url

### ISSUE THREAD

**Issue by klorydryk** [YunoHost-Apps/cryptpad_ynh#164]
Update from 4.11.0 to 5.2.1

When trying to open a pad from the main page from domaine pad.xxxx.com, it tries to open sandbox-pad.xxxx.com and fails.
Same with urls of documents previously created.
Thanks !

**Comment by Ddataa** [comment]
please confirm that you have setup the sandbox domain DNS and certificates

**Comment by rodinux** [comment]
Hello, it was ok after add the ssl certificate, sorry I forgot this open issue... 
Just something strange happens, the avatars of the users have been broken... I have made a mistake asking for keep `customize folder`, this version use a different files in `customize.dist`...

**Comment by rodinux** [comment]
well, in fact I have still a bug... I try restart the cryptpad service first to see what's happens... but I have to wait since I think my server is working with a task with Borg...

**Comment by b01xy** [comment]
To update from version 4.* to version 5.2.1 I had indeed to create, before the update, the sandbox-pad.xxxx.com vhost and certificate as said before
Could be good to write it in the documentation ?

**Comment by Billos** [comment]
I have the same issue.
My sandbox-pad DNS is configured, the certificate has been created, once I try to reach the user profile the loader gets stuck.

Also, the checkup page gives me the following error
`This instance has not been configured to enable support for embedding assets and documents in third-party websites. In order for this setting to be effective while still permitting encrypted media to load locally the Access-Control-Allow-Origin should only match trusted domains. Under most circumstances it is sufficient to permit only the sandbox domain to load assets. Remote embedding can be enabled via the admin panel.`

**Comment by Ddataa** [comment]
Can you share the error message that you see in the web browser when the page is not loading ?

Can you load the main page ?
Can you load a document page ?

please...

**Comment by Billos** [comment]
I can access the root page, then I can access the drive page, and all pages I'm trying to reach gets me stuck on this 
<img width="937" alt="image" src="https://user-images.githubusercontent.com/5809662/220940646-1bbb6279-5543-435a-a84a-498da4b70105.png">


The console gives me this
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/5809662/220941115-256ed38b-8331-41f4-899d-875e2a75c9e9.png">

**Comment by Billos** [comment]
Also, if I try to go to directly to the sandbox-pad url and create a user, once I try to login, I have an alert saying that this page is only reachable via the pad url

**Comment by Ddataa** [comment]
I can see in the error message that it is not trying to load the sandbox domain when he shall be.

You don't go directly to the sandbox domain, it is not mean for the users...

**Comment by Billos** [comment]
As I never could run the 5.x.x version I don't understand the problem 😅

My current configuration for the sandbox-pad is 
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/5809662/220945307-c64741e2-1103-4017-aa0f-ea74a465e512.png">

**Comment by Ddataa** [comment]
let me investigate and come back to you about it.

what version of cryptpad you were from before upgrading was it the latest available in yunohost ?

**Comment by Ddataa** [comment]
I did my tests when implementing, I installed the previous version and then did the upgrade with the new version on top of it, in a fresh yunohost install and it works.

I cannot predict each specific configuration of each yunohost install to assure upgrade will be always working.

@Billos 
If you don't have this issue then can we close it ?

**Comment by Billos** [comment]
I'll try to restore my old app, and update it.

You can close this
