### ISSUE TITLE
Failed upgrade to 1.27.0

### ISSUE THREAD

**Issue by croulibri** [YunoHost-Apps/cryptpad_ynh#21]
Hello,

I tried the upgrade to 1.22 version, but it failed when trying to update dependencies.
I am currently at 1.20 (I think)... indeed the info about the apps shows 1.15.0 but it seems the downloaded version is 1.20 and the upgrade should be 1.22.
Maybe the diversity of version between the `manifest.json`, the `app.src` and de readme is creating confusion during the upgrade precess.
I can send you some more info of the failed upgrade if you need.

Crou²

**Comment by frju365** [comment]
for the upgrade of dependencies, it's the manifest.json. You are right. But another problem stays after upgrade.

**Comment by frju365** [comment]
Surely something wrong in the command runned : bower install.

**Comment by frju365** [comment]
I tried to fix it in the upgrade branch. I will try to test it sooner as possible.

**Comment by croulibri** [comment]
Thanks @frju365 for your quick answer.
Hope you can fix the upgrade script!

**Comment by frju365** [comment]
bower ECONFLICT Unable to find suitable version for chainpad-netflux
... interesting. ok. I'm fixing first the installation, which is quite broken. I'll see how I can fix this conflict between dependencies.

**Comment by frju365** [comment]
In fact, I said that I wanted to modify the upgrade script... but I had some problem, with installation which took all my time.

**Comment by croulibri** [comment]
Thanks in advance for you work !

**Comment by croulibri** [comment]
For your information, I still have a proposed Cryptpad update in Yunohost admin page but it fails I think at the same place: 
```
Upgrade failed.

+ '[' 1 -eq 0 ']'

!!

+ local exit_code=1

cryptpad's script has encountered an error. Its execution was cancelled.

!!

+ ynh_exit_properly

bower ECONFLICT Unable to find suitable version for chainpad-netflux

bower chainpad-netflux#^0.6.1 validate 0.6.3 against https://github.com/xwiki-labs/chainpad-netflux.git#^0.6.1

bower chainpad-netflux#^0.6.1 cached https://github.com/xwiki-labs/chainpad-netflux.git#0.6.3

bower chainpad-netflux#^0.6.0 validate 0.6.3 against https://github.com/xwiki-labs/chainpad-netflux.git#^0.6.0

bower chainpad-netflux#^0.6.0 cached https://github.com/xwiki-labs/chainpad-netflux.git#0.6.3

bower html2canvas#^0.4.1 validate 0.4.1 against https://github.com/niklasvh/html2canvas.git#^0.4.1

bower html2canvas#^0.4.1 cached https://github.com/niklasvh/html2canvas.git#0.4.1

bower chainpad-listmap#^0.4.2 validate 0.4.3 against https://github.com/xwiki-labs/chainpad-listmap.git#^0.4.2

bower chainpad-listmap#^0.4.2 cached https://github.com/xwiki-labs/chainpad-listmap.git#0.4.3

bower sortablejs#^1.6.0 validate 1.6.0 against https://github.com/RubaXa/Sortable.git#^1.6.0

bower sortablejs#^1.6.0 cached https://github.com/RubaXa/Sortable.git#1.6.0

bower croppie#^2.5.0 validate 2.6.2 against https://github.com/Foliotek/Croppie.git#^2.5.0

bower croppie#^2.5.0 cached https://github.com/Foliotek/Croppie.git#2.6.2

+ sudo su -l cryptpad -s /bin/bash -c 'cd /var/www/cryptpad && env PATH=/opt/node_n/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin bower install'

updated 1 package in 11.681s

+ bower@1.8.4

/usr/local/bin/bower -> /usr/local/lib/node_modules/bower/bin/bower

+ sudo env PATH=/opt/node_n/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin npm install -g bower

+ sudo_path npm install -g bower

added 77 packages, removed 4 packages and updated 38 packages in 30.935s
```

**Comment by frju365** [comment]
Fixed.
