### ISSUE TITLE
Problème Installation.

### ISSUE THREAD

**Issue by frju365** [YunoHost-Apps/cryptpad_ynh#3]
Bonjour,
L'app ne fonctionne pas. Problème dans les dépendances + Type error. Une issue a été ouverte : https://github.com/xwiki-labs/cryptpad/issues/147.
Elle devrait être fixé avant la fin de la semaine, je l'espère.
frju365

**Comment by nemsia** [comment]
Salut,
Je viens de faire quelque tests rapide, si tu passe en directe sur le port 3000 (3001 dans mon cas avec mastodon qui tourne à coté) ça fonctionne.

Je regarde du coté de la conf nginx et du sso pour trouver le problème.
à bientôt.

**Comment by frju365** [comment]
Peux-tu faire une PR si tu trouves l'erreur ? (Je suis en vacances pour l'instant... je n'ai pas le temps pour l'instant de regarder et de trouver l'erreur sachant que je regarde mon ordinateur que très peu de temps) De plus l'erreur est un peut-être un peu plus compliqué que ce que j'ai mis dans l'en-tête.
Il y a en effet un problème au moment où on crée le pad : la page de chargement tourne sans s'arrêter (elle ne montre pas le pad). Mais si tu veux regarder, merci beaucoup !! (j'ai regardé avec cyp et on a eu des problèmes à comprendre ce problème...)

**Comment by nemsia** [comment]
Je cherche toujours...
J'ai le même problème, la page tourne sans charger le pad.
Je te tiens bien sur au courant si je trouve quelque chose.
Bonne vacances ;)

**Comment by JimboJoe** [comment]
Pour info, ça s'arrange dans [cette PR](https://github.com/YunoHost-Apps/cryptpad_ynh/pull/4) en cours :wink:

**Comment by nemsia** [comment]
Bonsoir,
Le dernier PR améliore beaucoup les choses mais que sous chrome... ou firefox sous android.
Sous firefox, avec gecko, le websocket cryptpad_websocket ne s'ouvre pas.
Je n'ai aucune explication.

**Comment by JimboJoe** [comment]
Oui, j'ai fini par remarquer la même chose ce soir. As-tu testé avec mon [dernier commit](https://github.com/YunoHost-Apps/cryptpad_ynh/commit/eb2883f9491b2d6b8fefaa26e8ea9668d1af91c0) ?

**Comment by nemsia** [comment]
Oui, Je viens de re-vérifier, le commit ne change rien.

**Comment by JimboJoe** [comment]
OK, merci. C'est quand même très bizarre, je ne produis plus le problème sous Firefox... Sans compter que je ne l'ai jamais produit sous Firefox en mode privé !

**Comment by nemsia** [comment]
Bonjour,
le problème venez de mon profil firefox, même en navigation privé...
Tout fonctionne avec un profil vierge.

**Comment by lapineige** [comment]
Ça fonctionne aussi de mon côté :)

**Comment by lapineige** [comment]
Ça fonctionne aussi de mon côté :)

**Comment by Rafi594** [comment]
Bonjour,

Moi j'ai un 502 bad gateway parce que le service cryptpad ne veut pas démarrer

**Comment by JimboJoe** [comment]
Peut-être que le démarrage est lent... Tu es sur un ARM ?
Il faudrait que l'on regarde ce qui a été fait sur etherpad_mypads [ici](https://github.com/YunoHost-Apps/etherpad_mypads_ynh/blob/master/scripts/install#L262-L288) pour attendre le démarrage du service.
Qu'en pensez-vous ?

**Comment by frju365** [comment]
Peut-on ouvrir une autre issue ? Car là le sujet a changé... et ce n'est plus trop clair. Dans une volonté d'organisation, je ferme cette issue. Est-ce que, @Rafi594, tu peux ouvrir une autre issue en mettant le serveur utilisé et le niveau de la RAM ? Sinon, je peux l'ouvrir, bien évidemment, mais ces informations sont précieuses, surtout si tu utilises un plateforme type raspberry pi.

**Comment by frju365** [comment]
Pour info : les derniers commits fixent l'erreur de départ ! :)
9d83186382ba04472ec7b73e6db29d71bf01133a
