### ISSUE TITLE
just white page

### ISSUE THREAD

**Issue by rocky-III** [YunoHost-Apps/cryptpad_ynh#37]
Just installed the news version of cryptpad - installation went find - gree light... 
but when i go to the domain I just get a wite page...

if I look up the scours code it will show:

```
<!DOCTYPE html>
<html class="cp" id="four-oh-four">
<!-- If this file is not called customize.dist/src/template.html, it is generated -->
<head>
    <title data-localization="main_title">CryptPad: Zero Knowledge, Collaborative Real Time Editing</title>
    <meta content="text/html; charset=utf-8" http-equiv="content-type"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="icon" type="image/png" href="/customize/main-favicon.png" id="favicon"/>
    <script async data-bootload="/customize/four-oh-four.js" data-main="/common/boot.js?ver=1.0" src="/bower_components/requirejs/require.js?ver=2.3.5"></script>
<script type="text/javascript" src="/ynh_portal.js"></script><link type="text/css" rel="stylesheet" href="/ynh_overlay.css"></link><script type="text/javascript" src="/ynhtheme/custom_portal.js"></script><link type="text/css" rel="stylesheet" href="/ynhtheme/custom_overlay.css"></link></head>
<body class="html">
<noscript>
<h1>404</h1>
<h3>We couldn't find the page you were looking for</h3>

</noscript>
```

**Comment by frju365** [comment]
yes... I finding very strange errors. I'm correcting these. Surely bad setting in Nginx :/

**Comment by rocky-III** [comment]
thanks for your work and please keep me updated

**Comment by rocky-III** [comment]
just tried it with the newes version again... same error... just white page

**Comment by frju365** [comment]
yes. I didn't achieve to solve the nginx problem.
Everything seem to be ok... but there is still this pb.

**Comment by klorydryk** [comment]
I confirm. If you need test or informations, let us know.

**Comment by JRelland** [comment]
Hi, thank you for creating this instance for YNH.

White Page on YunoHost 3.7.0.12 (now).


>   | <html class="cp" id="four-oh-four">
  | 
  | <head>
  | <title data-localization="main_title">CryptPad: Zero Knowledge, Collaborative Real Time Editing</title>
  | <meta content="text/html; charset=utf-8" http-equiv="content-type"/>
  | <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  | <link rel="icon" type="image/png" href="/customize/main-favicon.png" id="favicon"/>
  | <script async data-bootload="/customize/four-oh-four.js" data-main="/common/boot.js?ver=1.0" src="/bower_components/requirejs/require.js?ver=2.3.5"></script>
  | <script type="text/javascript" src="/ynh_portal.js"></script><link type="text/css" rel="stylesheet" href="/ynh_overlay.css"></link><script type="text/javascript" src="/ynhtheme/custom_portal.js"></script><link type="text/css" rel="stylesheet" href="/ynhtheme/custom_overlay.css"></link></head>
  | <body class="html">
  | <noscript>
  | <h1>404</h1>
  | <h3>We couldn't find the page you were looking for</h3>
  |  
  | </noscript>

**Comment by farvardin** [comment]
I've just stumbled upon this bug as well, I've noticed this:

bower_components/requirejs/require.js?ver=2.3.5 can't be loaded
/customize/four-oh-four.js can't be either

they call a 500 Internal Server Error

in the dev tools I can see a few errors as well:

> La ressource à l’adresse « https://jitsi.tricassinux.org/bower_components/requirejs/require.js?ver=2.3.5 » a été bloquée en raison d’un type MIME (« text/html ») incorrect (X-Content-Type-Options: nosniff).

Therefore the main page on the official cryptpad would report:

> <body class="html">
>     <noscript>
>         <p><strong>OOPS</strong> In order to do encryption in your browser, Javascript is really <strong>really</strong> required.</p>
>         <p><strong>OUPS</strong> Afin de pouvoir réaliser le chiffrement dans votre navigateur, Javascript est <strong>vraiment</strong> nécessaire.</p>
>     </noscript>
> </html>
> 

while the yunohost installation would say instead:

> <body class="html">
> <noscript>
> <h1>404</h1>
> <h3>We couldn't find the page you were looking for</h3>
>

**Comment by klorydryk** [comment]
@ericgaspar is it solved?

**Comment by ericgaspar** [comment]
If this is still a problem, It is better to open a new issue.
