### ISSUE TITLE
Cannot access the admin area

### ISSUE THREAD

**Issue by tiotrom** [YunoHost-Apps/cryptpad_ynh#65]
I am sorry for not following the template, but the issue is this: I run the latest YunoHost + latest Cryptpad. I installed it correctly. All fine. I made an account.  Then edited var/www/cryptpad/config/config.js. and added my account's public key. Restarted cryptpad. Tried to access /admin and I get "Only administrators can access this page". Also rebooted the server just in case. Am I doing something wrong? Thanks!

**Comment by ericgaspar** [comment]
Your problem looks similar to this one on the forum : https://forum.yunohost.org/t/cryptpad-online-office-editor/11924/8

**Comment by tiotrom** [comment]
Thanks works now after I removed the // before the key. Cheers!
