### ISSUE TITLE
Upgrade failed

### ISSUE THREAD

**Issue by TheNomad11** [YunoHost-Apps/cryptpad_ynh#72]
**Describe the bug**
Upgrade failed
- Hardware: *VPS bought online 
- YunoHost version: 4.1.7

See here: https://paste.yunohost.org/raw/onaketetik

**Comment by stemy2** [comment]
Same.

https://paste.yunohost.org/raw/acaladanud

**Comment by ericgaspar** [comment]
Sorry I set a wrong shasum... 🙄 It should be ok to upgrade now with `sudo yunohost app upgrade cryptpad -u https://github.com/YunoHost-Apps/cryptpad_ynh/`

**Comment by stemy2** [comment]
It works !

Dumb question: why does the other command still fails while this one does not ?

**Comment by TheNomad11** [comment]
Even more dumb question: Why did this command work for you @stemy2 but not for me? 

Upgrade failed again.

Here are the logs 
https://paste.yunohost.org/raw/ugohumilax

I even got the scary message 

> This action broke dpkg/APT (the system package managers)... You can try to solve this issue by connecting through SSH and running `sudo apt install --fix-broken` and/or `sudo dpkg --configure -a`.

**Comment by rocky-III** [comment]
same here....  even  `sudo yunohost app upgrade cryptpad -u https://github.com/YunoHost-Apps/cryptpad_ynh/` does not work
same as @TheNomad11

**Comment by TheNomad11** [comment]
Now I have the newest version 4.2.1 running! Interestingly enough, installing the newest version worked!
I deinstalled the old version, and then installed the newest version. All my data is still there, that is all previously created test documents

**Comment by TheNomad11** [comment]
but after playing around a bit, in the settings I was asked to upgrade my account to get the newest features, I did so, but after that I was not able to log in again, "invalid user or password", weird stuff, not sure how this could happen. I then signed up with the same username and password and everything was gone...

**Comment by TROMsite** [comment]
Upgrade  from 4.2.1~ynh2 to 4.3.0~ynh1  failed https://paste.yunohost.org/raw/xuxagewege

**Comment by cl3f3** [comment]
Mise à jour impossible aussi : https://paste.yunohost.org/raw/tavehujiza

**Comment by ericgaspar** [comment]
Would you mind upgrading with the testing version see if it works?  `sudo yunohost app upgrade cryptpad -u https://github.com/YunoHost-Apps/cryptpad_ynh/tree/testing`

**Comment by TROMsite** [comment]
To add more info to this, when I tried to update it from the panel I also saw this error:
```
Something went wrong while updating the cache of APT (Debian's package manager). Here is a dump of the sources.list lines, which might help identify problematic lines:
sources.list:deb http://asi-fs-n.contabo.net/debian buster main non-free contrib
sources.list:deb-src http://asi-fs-n.contabo.net/debian buster main non-free contrib
sources.list:deb http://security.debian.org/debian-security buster/updates main contrib non-free
sources.list:deb-src http://security.debian.org/debian-security buster/updates main contrib non-free
sources.list:deb http://asi-fs-n.contabo.net/debian buster-updates main contrib non-free
sources.list:deb-src http://asi-fs-n.contabo.net/debian buster-updates main contrib non-free
sources.list.d/mobilizon.list:deb http://packages.erlang-solutions.com/debian buster contrib
sources.list.d/crystal.list:deb https://dl.bintray.com/crystal/deb all stable
sources.list.d/yunohost.list:deb https://forge.yunohost.org/debian/ buster stable
sources.list.d/invidious.list:deb https://dl.bintray.com/crystal/deb all stable
sources.list.d/onlyoffice.list:deb http://download.onlyoffice.com/repo/debian squeeze main
sources.list.d/webmin.list:deb http://download.webmin.com/download/repository sarge contrib
```
Do you think is related?

**Comment by cl3f3** [comment]
> Would you mind upgrading with the testing version see if it works? `sudo yunohost app upgrade cryptpad -u https://github.com/YunoHost-Apps/cryptpad_ynh/tree/testing`

Same issue (same as `sudo yunohost app upgrade cryptpad -u https://github.com/YunoHost-Apps/cryptpad_ynh/`)

**Comment by TROMsite** [comment]
Any news about this? I don't know how we should proceed now...the upgrade does not work. Is there a way to force it? Or to reinstall as new but bring back the data so we dont lose the users and their files?

**Comment by TROMsite** [comment]
This is the error log for the latest update try https://paste.yunohost.org/raw/durepihiku

Snippet:
```
2021-04-18 21:37:28,036: DEBUG - 32892 + action=reload-or-restart
2021-04-18 21:37:28,036: DEBUG - 32892 + systemctl reload-or-restart nginx
2021-04-18 21:37:28,638: DEBUG - 33496 + [[ -n '' ]]
2021-04-18 21:37:28,840: DEBUG - 33698 + echo '[####################] > Restoration completed for CryptPad'
2021-04-18 21:37:28,841: DEBUG - 33698 + ynh_exit_properly
2021-04-18 21:37:28,841: DEBUG - 33698 + local exit_code=0
2021-04-18 21:37:28,841: DEBUG - 33698 + '[' 0 -eq 0 ']'
2021-04-18 21:37:28,841: DEBUG - 33699 + exit 0
2021-04-18 21:37:28,942: DEBUG - 33740 To view the log of the operation 'Restore 'cryptpad' from a backup archive', use the command 'yunohost log display 20210418-193711-backup_restore_app-cryptpad'
2021-04-18 21:37:29,444: DEBUG - 34281 The permission database has been resynchronized
2021-04-18 21:37:30,146: DEBUG - 34993 SSOwat configuration regenerated
2021-04-18 21:37:30,146: WARNING - sh: 0: getcwd() failed: No such file or directory
2021-04-18 21:37:30,147: DEBUG - 35008 Restoration completed
2021-04-18 21:37:30,147: WARNING - sh: 0: getcwd() failed: No such file or directory
2021-04-18 21:37:30,147: DEBUG - 35009 action [11065.1] executed in 34.859s
2021-04-18 21:37:30,147: WARNING - sh: 0: getcwd() failed: No such file or directory
2021-04-18 21:37:30,147: DEBUG - apps:
2021-04-18 21:37:30,147: DEBUG -   cryptpad: Success
2021-04-18 21:37:30,147: DEBUG - system:
2021-04-18 21:37:30,248: DEBUG - + ynh_die '--message=The app was restored to the way it was before the failed upgrade.'
2021-04-18 21:37:30,248: WARNING - The app was restored to the way it was before the failed upgrade.
2021-04-18 21:37:30,249: DEBUG - + ret_code=1
2021-04-18 21:37:30,250: DEBUG - + echo 'The app was restored to the way it was before the failed upgrade.'
2021-04-18 21:37:30,250: DEBUG - + exit 1
2021-04-18 21:37:30,399: ERROR - Could not upgrade cryptpad: An error occurred inside the app upgrade script
```

**Comment by TROMsite** [comment]
Upgrade to 4.4.0~ynh1 failed again. Logs https://paste.yunohost.org/raw/hisuforupo - Is there any way to fix this? Or should we just reinstall Cryptpad and if so how to restore the configs and data?

**Comment by ericgaspar** [comment]
Sorry for the delay in replying.
It seems that `bower` is not found o_O : `/usr/share/yunohost/helpers.d/logging: line 145: bower: command not found`
would you mind trying to upgrade with this branch
`sudo yunohost app upgrade cryptpad -u https://github.com/YunoHost-Apps/cryptpad_ynh/tree/bower`
but the problem could be something else... (I see a lot of this: `getcwd() failed: No such file or directory` that I am unable to understand)

**Comment by cl3f3** [comment]
Upgrade to 4.4.0~ynh1 failed for the same reasons of 4.3.0. https://paste.yunohost.org/raw/ibeyediquy

**Comment by TROMsite** [comment]
>  sudo yunohost app upgrade cryptpad -u https://github.com/YunoHost-Apps/cryptpad_ynh/tree/bower

Worked! Awesome! Finally!

But all of the config was erased so I had to redo everything. Maybe do not modify the file var/www/cryptpad/config/config.js ?

**Comment by ericgaspar** [comment]
@cl3f3 Can you confirm that you are upgrading from this branch?
`sudo yunohost app upgrade cryptpad -u https://github.com/YunoHost-Apps/cryptpad_ynh/tree/bower`
The logs seem to show master branch upgrade ...

**Comment by ericgaspar** [comment]
@TROMsite 

> Manually-modified files should have been automatically backuped inside `/home/yunohost.conf/backup/` before they get replaced (and a warning message should have shown you the diff)

But yes it is not super admin friendly... should be fixed with #82

**Comment by cl3f3** [comment]
> @cl3f3 Can you confirm that you are upgrading from this branch?
> `sudo yunohost app upgrade cryptpad -u https://github.com/YunoHost-Apps/cryptpad_ynh/tree/bower`
> The logs seem to show master branch upgrade ...

It works !
`admin@ynh:~$ sudo yunohost app upgrade cryptpad -u https://github.com/YunoHost-Apps/cryptpad_ynh/tree/bower
Info: Now upgrading cryptpad...
Info: [....................] > Loading installation settings...
Info: [....................] > Ensuring downward compatibility...
Info: [+...................] > Backing up CryptPad before upgrading (may take a while)...
Info: [#...................] > Stopping a systemd service...
Info: [#...................] > Making sure dedicated system user exists...
Info: [#...................] > Upgrading source files...
Info: [#+..................] > Upgrading NGINX web server configuration...
Info: [##+.................] > Upgrading dependencies...
Info: [###+++++++++++++++..] > Building CryptPad... (this will take some time and resources!)
Info: [##################..] > Upgrading systemd configuration...
Info: [##################+.] > Integrating service in YunoHost...
Info: [###################.] > Starting a systemd service...
Info: The service cryptpad has correctly executed the action start.
Info: [###################.] > Reloading NGINX web server...
Info: [####################] > Upgrade of CryptPad completed
Success! cryptpad upgraded
Success! Upgrade complete`

**Comment by ericgaspar** [comment]
Closing with #83. Please open a new issue if you still have upgrade issues
