### ISSUE TITLE
several problems with the new version

### ISSUE THREAD

**Issue by boistordu** [YunoHost-Apps/cryptpad_ynh#84]
--- 

**Describe the bug**
fresh installation because the upgrade of last night failed and I could not restore the installation.
Maybe I'm wrong but at level 7 the cryptpad should recognize the accounts installed on the system no?
For me it does not.
I can't also load the /admin section. It hangs a load shared folder. I've tested on multiple hosts, multiple browsers.

Any ideas on how to debug this?

**Versions**
- Hardware: *VM on i7 4vcore 12GB ...*
- YunoHost version: 4.1.8

**Comment by ericgaspar** [comment]
> Maybe I'm wrong but at level 7 the cryptpad should recognize the accounts installed on the system no?

CryptPad does not support LDAP so it does not recognize YunoHost account (nothing to do with the app being level 7)

For the admin, did you modify the `config.js` file to be admin?
https://github.com/YunoHost-Apps/cryptpad_ynh/blob/3499c4d1d7e41737feb7923c99a499215918662c/conf/config.js#L108-L124

PS: please clean up you issue report: out of it, only 5 lines are meaningful

**Comment by boistordu** [comment]
No modification whatsoever . It's a fresh installation as I said since it's an after failed upgrade

**Comment by ericgaspar** [comment]
So ... you need to set your admin key in `config.js` in order to have access to `/admin`

**Comment by boistordu** [comment]
Ah, i didn't know that. It would be nice if we got a service mail about it like we have on other apps so that we know that nothing is yet set up.

**Comment by ericgaspar** [comment]
Good idea. #87 should clarify post install process

**Comment by boistordu** [comment]
now the admin part works indeed. 
thanks I will close this issue now.
